spring.application.name=spring-ai
spring.ai.mcp.server.name=masud-mcp
spring.ai.mcp.server.version=1.0.0

#Config for MCP server
spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.type=async
