spring.application.name=dog-adoption
server.port=4000
spring.ai.mcp.server.name=mcp-adoption
spring.ai.mcp.server.version=1.0.0

#Config for MCP server
spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.type=async

#DB
spring.datasource.url=jdbc:postgresql://localhost:5432/dog-adoption-service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
